<div style={{ display: faqs ? 'block' : 'none' }}>
    <div className="text-left">
        <h3 className="text-center">Glossary</h3>
        <h5 className="mt-3">Algorithm</h5>
        A procedure that is carried out in sequential steps to solve a problem.
        <h5 className="mt-3">Balance</h5>
        The amount of money a player has in their wallet or account.
        <h5 className="mt-3">Bust</h5>
        The depletion of a player’s balance.
        <h5 className="mt-3">Cryptography</h5>
        The method of making information secure.
        <h5 className="mt-3">Deterministic</h5>
        An algorithm that when given a particular input, will always produce the same output.
        <h5 className="mt-3">Hash</h5>
        A cryptographic hash function takes any input, such as a file, image or text and transforms it into fixed-sized alphanumeric string called a ”hash”. This is a one-way process meaning, that when you are given a hash, there is no feasible way to know the original input that created it. The slightest change to the input will have a significant, human readable change to the hash. This deterministic feature is what makes hashing the perfect solution for verifying that two inputs are in fact, the same.
        <h5 className="mt-3">House Edge</h5>
        A percentage of each wager(usually only the winning bets apply) that an online casino keeps for itself. In a physical casino and some online games such as roulette, the house edge refers to the expectation of loses from the player due to the mathematical advantage the casino has over you based on each specific game’s design.
        <h5 className="mt-3">Nonce</h5>
        A nonce is a number added to the end of a seed and is only used once per seed. A nonce does not have to be secret or unpredictable, but it must be unique so iit can also be used as a counter.
        <h5 className="mt-3">Provably Fair</h5>
        Is a term that describes how the results generated by an RNG were not manipulated by the casino.
        <h5 className="mt-3">Random Number Generator</h5>
        Or RNG, is a device or algorithm that generates a sequence of numbers that has no set pattern.
        <h5 className="mt-3">Result</h5>
        The outcome generated by the RNG.
        <h5 className="mt-3">Rigged</h5>
        In an online casino’s chat room, you can find people using this term as a way to justify the money they just lost because of their conscious decision to gamble.
        <h5 className="mt-3">Salt</h5>
        A value that is attached to an input before hashing , that is unique to a specific user.
        <h5 className="mt-3">Seed</h5>
        In a provably fair system, this is the data that is used by an RNG to generate the results of a game. The server seed is provided by the operator. The client seed is provided by the player so that the player is involved in the game’s outcome.
        <h5 className="mt-3">SHA-256</h5>
        SHA is an acronym for “Secure Hash Algorithms”. The 256 just refers to the SHA-2 family of hash functions and is most commonly used by crypto gambling sites. These are military-grade cryptographic hash functions and they have been standardized by the U.S. National Institute of Standards and Technology (NIST).
        <h5 className="mt-3">Wager</h5>
        The amount that a player risks per round.
    </div>
</div>